application: kubernetes-worker
charm: kubernetes-worker
settings:
  channel:
    default: 1.12/stable
    description: |
      Snap channel to install Kubernetes worker services from
    source: default
    type: string
    value: 1.12/stable
  http_proxy:
    default: ""
    description: |
      URL to use for HTTP_PROXY to be used by Docker. Only useful in closed
      environments where a proxy is the only option for routing to the
      registry to pull images
    source: default
    type: string
    value: "http://roos-proxy.ddmi.intra.renhsc.com:3128/"
  https_proxy:
    default: ""
    description: |
      URL to use for HTTPS_PROXY to be used by Docker. Only useful in closed
      environments where a proxy is the only option for routing to the
      registry to pull images
    source: default
    type: string
    value: "http://roos-proxy.ddmi.intra.renhsc.com:3128/"
  no_proxy:
    default: ""
    description: |
      Comma-separated list of destinations (either domain names or IP
      addresses) that should be directly accessed, by opposition of going
      through the proxy defined above. Must be less than 2023 characters long
    source: user
    type: string
    value: localhost,.renhsc.com,artifactory,localhost,.renhsc.com,.nonprd.local,10.145.8.1,10.145.8.2,10.145.8.3,10.145.8.4,10.145.8.5,10.145.8.6,10.145.8.7,10.145.8.8,10.145.8.9,10.145.8.10,10.145.8.11,10.145.8.12,10.145.8.13,10.145.8.14,10.145.8.15,10.145.8.16,10.145.8.17,10.145.8.18,10.145.8.19,10.145.8.20,10.145.8.21,10.145.8.22,10.145.8.23,10.145.8.24,10.145.8.25,10.145.8.26,10.145.8.27,10.145.8.28,10.145.8.29,10.145.8.30,10.145.8.31,10.145.8.32,10.145.8.33,10.145.8.34,10.145.8.35,10.145.8.36,10.145.8.37,10.145.8.38,10.145.8.39,10.145.8.40,10.145.8.41,10.145.8.42,10.145.8.43,10.145.8.44,10.145.8.45,10.145.8.46,10.145.8.47,10.145.8.48,10.145.8.49,10.145.8.50
  docker-logins:
    default: '[]'
    description: |
      Docker login credentials. Setting this config allows Kubelet to pull images from
      registries where auth is required.

      The value for this config must be a JSON array of credential objects, like this:
        [{"server": "my.registry", "username": "myUser", "password": "myPass"}]
    source: user
    type: string
    value: '[{"server": "https://artifactory:5000", "username": "rvandermey", "password":
      "myapikey"}]'
