#!/bin/bash
## MAAS Login Script

## Pull profile/user name from commandline argument
PROFILE=$1

## Set your MAAS API IP:Port here
MAAS_IP="172.1.0.1:5240"
MAAS_URL="http://$MAAS_IP/MAAS/api/2.0/"

## Script will check for username on commandline 
## If none is given, login will continue with the current username environment variable
[[ ! -z $PROFILE ]] || PROFILE=$(whoami)

## Define API Key File Location
API_KEY_FILE="~/.config/${PROFILE}-MAAS-API-KEY.txt"

## Function to create $PROFILE Key File
get_maas_key() {
sudo maas-region apikey --username=$PROFILE > $API_KEY_FILE
}

## Check for $PROFILE Key File
## If none is found, will generate key file
[[ -f $API_KEY_FILE ]] || get_maas_key

# Login to MAAS API using $PROFILE & Key File
maas login $PROFILE $MAAS_URL - < $API_KEY_FILE
